# Generated by Django 6.0.6 on 2026-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_estimated_hours_task_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Backlog', max_length=50),
        ),
    ]
